name: m_and_r_quiz_admin_panel
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  #Google Font
  google_fonts: ^6.2.1

  #API Handler
  dio: ^5.5.0+1
  
  #Device Info
  device_info_plus: ^10.1.2

  #Session Helper
  shared_preferences: ^2.2.3

  # Network Image
  image_network: ^2.5.6

  #API handler
  toastification:  ^2.0.0

  #Hover Flutter
  hovering: ^1.0.4

  #Scrool Index
  scroll_to_index: ^3.0.1

  #DATE FORMATTER
  intl: ^0.19.0

  #Carousel Slider
  carousel_slider: ^5.0.0

  #Smooth Page Indicator
  smooth_page_indicator: ^1.2.0+3
  ########################################## ROUTING ##########################################
  go_router: ^14.2.1

  ############################# PICKER ########################
  image_picker: ^1.1.2
  file_picker: any
  universal_io: ^2.2.2


  ################################  ANIMATION  ################################
  flutter_animate: ^4.5.0

  #Url Launcher
  url_launcher: ^6.3.0
  flutter_custom_tabs: ^2.1.0

  ################################ QUILL EDITOR ########################
  flutter_quill: ^10.8.2
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_extensions: ^10.8.2
  flutter_quill_delta_from_html: ^1.4.1
  # html_editor_enhanced: ^2.6.0

  ######################################### FIREBASE ########################################
  #Core
  firebase_core: ^3.2.0
  #Firebase Storage
  firebase_storage: ^12.1.1
  #Cloud Firestore
  cloud_firestore: ^5.1.0

  #Responsive Grid
  responsive_grid_list: ^1.4.0
  #Country Code
  country_code_picker: ^3.0.0

  # Country State City
  country_state_city: ^0.1.6

  #HTML View
  flutter_widget_from_html: ^0.15.2
  fwfh_cached_network_image: ^0.14.3
  fwfh_url_launcher: ^0.9.1
  fwfh_chewie: ^0.14.8

  #HTML
  html: ^0.15.4
  
  #Lottie
  lottie: ^3.1.3
  

  #HTTPs
  http: ^1.2.2
  http_downloader: ^0.0.2

  glass_kit: ^4.0.1

dependency_overrides:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

  pretty_dio_logger: ^1.4.0

  

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/lottie_animations/
    - assets/page_not_found.html
    - assets/icons/

flutter_assets:
  assets_path: assets/
  output_path: lib/genrated/
  filename: assets.dart



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

